### ISSUE TITLE
Account Owner acceptance required

### ISSUE THREAD

**Issue by matthewmrotter** [jimstrike/craft-siteimprove-cms-plugin#1]
We just got a trial of SiteImprove and logged in through the plugin but received this message:

> Account Owner acceptance required
> In order for you to start using the Siteimprove CMS-plugin the Account Owner must agree to the Terms & Conditions. The Account Owner will be prompted for this when logging into the CMS-plugin for the first time.
> 

We were not given the option of accepting Terms & Conditions and can't find anywhere in the dashboard to accept. 

Additionally, the "need help" link goes to a 404

**Comment by jimstrike** [comment]
> We just got a trial of SiteImprove and logged in through the plugin but received this message:
> 
> > Account Owner acceptance required
> > In order for you to start using the Siteimprove CMS-plugin the Account Owner must agree to the Terms & Conditions. The Account Owner will be prompted for this when logging into the CMS-plugin for the first time.
> 
> We were not given the option of accepting Terms & Conditions and can't find anywhere in the dashboard to accept.
> 
> Additionally, the "need help" link goes to a 404

**Comment by jimstrike** [comment]
@matthewmrotter, sorry for late reply. I believe the message you received above comes from Siteimprove.com itself and has nothing to do with "Siteimprove CMS Plugin" plugin for Craft CMS. 

I suggest to login first via [Siteimprove.com](https://siteimprove.com/) website and agree to the terms & conditions there before using this plugin on your Craft website. As the message mentions:

> The Account Owner will be prompted for this when logging into the CMS-plugin for the first time.

Let me know if you are still having issues.
